all:
  children:
    rhel_vms:
      hosts:
        tf-rhel-01:
          ansible_host: 192.168.122.100
          ansible_user: admin
          ansible_python_interpreter: /usr/bin/python3
          ansible_ssh_common_args: "-o ProxyJump=Placeholder@hypervisor"
