---
- name: Show distribution
  ansible.builtin.debug:
    msg: "{{ ansible_facts['distribution'] }} {{ ansible_facts['distribution_version'] }}"

- name: Check hostname
  ansible.builtin.command: hostnamectl --static
  register: hostname_result
  changed_when: false

- name: Show hostname
  ansible.builtin.debug:
    var: hostname_result.stdout

- name: Check failed systemd units
  ansible.builtin.command: systemctl --failed --no-pager
  register: failed_units
  changed_when: false

- name: Show failed systemd units
  ansible.builtin.debug:
    var: failed_units.stdout_lines

- name: Ensure qemu guest agent is running
  ansible.builtin.systemd_service:
    name: qemu-guest-agent
    state: started
    enabled: true
  become: true
