---
- name: Ensure sshd is running
  ansible.builtin.systemd_service:
    name: sshd
    state: started
    enabled: true
  become: true

- name: Ensure qemu guest agent is running
  ansible.builtin.systemd_service:
    name: qemu-guest-agent
    state: started
    enabled: true
  become: true

- name: Check firewalld status
  ansible.builtin.command: systemctl is-active firewalld
  register: firewalld_status
  changed_when: false
  failed_when: false

- name: Show firewalld status
  ansible.builtin.debug:
    var: firewalld_status.stdout
